---
title: "precancer_atlas_example"
vignette: >
  %\VignetteIndexEntry{precancer_atlas_example}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---

```{r}
#| label: setup
options(paged.print=FALSE)
```

```{r}
library(tidyverse)
```


```{r}
devtools::load_all(".")
seu <- readRDS("~/Documents/Work_Projects/precancer-atlas-code/data/atlas_data/main_seurat_data.RDS")
# seu <- readRDS("~/Documents/Work_Projects/precancer-atlas-code/data/atlas_data/CD4T_v2_18Feb2025.RDS")
meta_data <- readr::read_tsv("~/Documents/Work_Projects/precancer-atlas-code/data/atlas_data/meta_data.tsv.gz") |>
  left_join(readRDS("~/Documents/Work_Projects/precancer-atlas-code/data/atlas_data/all_treelabels.RDS"), by = "cell_id") |>
  dplyr::select(- starts_with("manual_cell_type"))

```


```{r}
# SeuratObject::Assays(seu)
# tmp <- seu[["RNA"]]
sce <- Seurat::as.SingleCellExperiment(seu)
SummarizedExperiment::colData(sce) <- SummarizedExperiment::colData(sce) |>
  as_tibble() |>
  left_join(meta_data, by = "cell_id") |>
  S4Vectors::DataFrame()
`%not_in%` <- Negate(`%in%`)
data_filter <- rlang::quo(disease_state %not_in% c("pre_non_malignant", "pre_virus") &
                            cancer != "LIHC" &
                            disease_state_details != "Tumor_metastasis" &
                            additional_information != "Non-atrophic gastritis" & donor != "P154")

sel_cells <- sce$cell_id[rlang::eval_tidy(data_filter,  as_tibble(SummarizedExperiment::colData(sce)))]
sce <- sce[,which(sce$cell_id %in% sel_cells)]
rm(seu)
```


```{r}
hvg <- order(-MatrixGenerics::rowVars(logcounts(sce)))
sce <- sce[hvg[1:500], ]
```


```{r}
sce <- sce[,sce$cancer %in% c("LUAD", "BRCA", "LUSC", "PDAC")]
# sce <- sce[,sample.int(ncol(sce), size = 5000)]
```

```{r}
sce$stage <- as.character(sce$stage)
spec <- init_shinyTreelabel(sce, 
                    treelabels = c("label_manual", "label_immuneA", "label_lung"),
                    design = \(dat){
                      ~ stage
                    }, 
                    pseudobulk_by = vars(donor), 
                    metaanalysis_over = c("cohort", "cancer"),
                    gene_expr_by = "stage",
                    contrast = vars(cond(stage = "Pre") - cond(stage = "Normal"),
                                    cond(stage = "Tumor") - cond(stage = "Normal"),
                                    cond(stage = "Tumor") - cond(stage = "Pre")),
                    de_test = "limma")
saveRDS(spec, "~/Downloads/result_cache/atlas_small-spec.RDS")
```


```{r}
spec <- init_shinyTreelabel(sce, 
                    treelabels = c("label_immuneA"),
                    design = \(dat){
                      ~ stage
                    }, 
                    pseudobulk_by = vars(donor), 
                    metaanalysis_over = c("cohort", "cancer"),
                    gene_expr_by = "stage",
                    contrast = vars(cond(stage = "Pre") - cond(stage = "Normal"),
                                    cond(stage = "Tumor") - cond(stage = "Normal"),
                                    cond(stage = "Tumor") - cond(stage = "Pre")),
                    de_test = "glmGamPoi")
precalc_res2 <- precalculate_results(spec, sce, dbfile = "~/Downloads/result_cache/tmp.duckdb", output = c("de"), clear_file = TRUE)
```


```{r}
system.time(
  precalc_res <- precalculate_results(spec, sce, dbfile = "~/Downloads/result_cache/atlas_small.duckdb", output = c("de", "de_meta"), clear_file = FALSE)
)

```




```{r}
spec <- readRDS("~/Downloads/result_cache/atlas_small-spec.RDS")
make_treelabel_app(spec, sce, precalc_results = "~/Downloads/result_cache/atlas_small.duckdb")
# run_shinyTreelabel(spec, sce, precalc_results = "~/Downloads/result_cache/cd4.duckdb")
```


```{r}
sce$label_manual
```


```{r}
library(shinyTreelabel)
spec <- readRDS("~/shinyTreelabel_data/atlas-spec.RDS")
run_shinyTreelabel(spec, precalc_results = "~/shinyTreelabel_data/atlas.duckdb", 
                   options = list(port = 4798))
```


